config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  resources :trails do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :trail
end

app/models/trail.rb
class Trail < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :name, presence: true
  validates :description, presence: true, length: { maximum: 500 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "user", password: "password", only: :destroy

  def create
    @trail = Trail.find(params[:trail_id])
    @comment = @trail.comments.create(comment_params)
    redirect_to trail_path(@trail)
  end

  def destroy
    @trail = Trail.find(params[:trail_id])
    @comment = @trail.comments.find(params[:id])
    @comment.destroy
    redirect_to trail_path(@trail)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/trails_controller.rb
class TrailsController < ApplicationController

  http_basic_authenticate_with name: "user", password: "password", except: [:index, :show]

  def index
    @trails = Trail.all
  end

  def show
    @trail = Trail.find(params[:id])
  end

  def new
    @trail = Trail.new
  end

  def edit
    @trail = Trail.find(params[:id])
  end

  def create
    @trail = Trail.new(trail_params)
    if @trail.save
      redirect_to @trail
    else
      render 'new'
    end
  end

  def update
    @trail = Trail.find(params[:id])

    if @trail.update(trail_params)
      redirect_to @trail
    else
      render 'edit'
    end
  end

  def destroy
    @trail = Trail.find(params[:id])
    @trail.destroy

    redirect_to trails_path
  end

  private
    def trail_params
      params.require(:trail)
      .permit(
        :name,
        :description,
        :latitude,
        :longitude,
        :difficulty,
        :direction
      )
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/trails_helper.rb
module TrailsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
<p>
  <%= link_to 'Delete Comment',
    [comment.trail, comment],
      method: :delete,
      data: { confirm: 'Are your sure?'}
  %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [@trail, @trail.comments.build], local: true) do |form| %>
<p>
  <%= form.label :commenter %>
  <%= form.text_field :commenter %>
</p>
<p>
  <%= form.label :body %>
  <%= form.text_area :body %>
</p>
<p>
  <%= form.submit %>
</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HikePlanner</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/trails/_form.html.erb
<%= form_with(model: @trail, local: true, class: 'trail-form') do |form| %>

  <% if @trail.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@trail.errors.count, "error") %> in trail submission:
      </h2>
      <ul>
        <% @trail.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Trail Name -->
  <div class="trail-form__item">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <!-- Trail Description -->
  <div class="trail-form__item">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <!-- Trail Start Coordinates -->
  <div class="trail-form__item">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <!-- Trail Difficulty -->
  <div class="trail-form__item">
    <%= form.label :difficulty %>
    <%= form.select(:difficulty, options_for_select([['Light', 1], ['Moderate', 2], ['Strenuous', 3]])) %>
  </div>

  <!-- Trail Direction -->
  <div class="trail-form__item">
    <%= form.label :direction %>
    <%= form.select(:direction, options_for_select([['Out & Back', 1], ['Loop', 2]])) %>
  </div>

  <!-- Submit Button -->
  <div class="trail-form__item">
    <%= form.submit %>
  </div>
<% end %>

app/views/trails/edit.html.erb
<h1>Update Trail</h1>

<%= render 'form' %>

<%= link_to 'Back', trails_path, class: 'btn' %>

app/views/trails/index.html.erb
<h2>Trails On Record</h2>

<ul class="trail-list">
  <% @trails.each do |trail| %>
    <li class="trail-list__item">
      <p class="trail-list__item__title"><%= trail.name %></p>
      <div class="trail-list__item__controls">
        <%= link_to 'Show', trail_path(trail), class: 'btn' %>
        <%= link_to 'Edit', edit_trail_path(trail), class: 'btn' %>
        <%= link_to 'Delete', trail_path(trail), {
                method: :delete,
                data: { confirm: 'Are you sure?' },
                class: 'btn'
                } %>
      </div>
    </li>
  <% end %>
</ul>
<%= link_to 'Back', root_path, class: 'btn' %>

app/views/trails/new.html.erb
<h1>Create a New Trail</h1>

<%= render 'form' %>

<%= link_to 'Back', trails_path, class: 'btn' %>

app/views/trails/show.html.erb
<h1>Trail Information</h1>

<div class="trail-info">
  <p>
    <strong>Name:</strong>
    <%= @trail.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @trail.description %>
  </p>

  <p>
    <strong>Latitude:</strong>
    <%= @trail.latitude %>
  </p>

  <p>
    <strong>Longitude:</strong>
    <%= @trail.longitude %>
  </p>

  <p>
    <strong>Difficulty:</strong>
    <div class="difficulty-marker"></div>
    <% if @trail.difficulty > 1 %>
      <div class="difficulty-marker"></div>
    <% end %>
    <% if @trail.difficulty > 2 %>
      <div class="difficulty-marker"></div>
    <% end %>
  </p>

  <p>
    <strong>Direction:</strong>
    <% if @trail.direction == 1 %>
    Out & Back
    <% else %>
    Loop
    <% end %>
  </p>
</div>

<%= link_to 'Edit Trail', edit_trail_path(@trail), class:'btn' %>
<%= link_to 'Back', trails_path, class:'btn' %>

<div class="comments-box">
  <h2>Comments</h2>
  <%= render @trail.comments %>
  <h2> Add a comment </h2>
  <%= render 'comments/form' %>
</div>

app/views/welcome/index.html.erb
<h1>Trails</h1>
<h2>Hike Planner</h2>
<%= link_to 'Trails', { controller: 'trails' }, { class: 'btn' } %>
<%= link_to 'Add a Trail', { controller: 'trails', action: 'new' }, { class: 'btn' } %>